### ISSUE TITLE
User should be able to mint their own NFTs

### ISSUE THREAD

**Issue by danishyasin33** [robor-systems/agoric-card-store#5]
The current marketplace has the features of primary and secondary marketplaces. But we want to provide users the ability to mint their own NFTs. 
For that purpose we will have a screen within the existing marketplace that will have a form where users can input all the required fields and mint their own NFTs in their wallets. 
This is an extension of #2

**Comment by danishyasin33** [comment]
@haseebasim you can already start building the mint contract with a very basic UI.

**Comment by aamnasarosh** [comment]
Added the 'Create' link in current flow: https://xd.adobe.com/view/d825c6e4-887c-4432-9c98-5fce91a25cb2-8d76/

@danishyasin33 please review

**Comment by haseebasim** [comment]
### Update 27th January, 2022
---
- Hussain and I `merged` our respective codes from `atomic-swap-2` and `atomic-swap-abstraction` today and removed any conflicts and errors that occurred. 
- Created a `dummy form`, that the user can interact with to provide some data regarding the NFT they want to add.
- Integrated `Pinata gateway` to host NFT images over ipfs. 
- Added `minting functionality` to the current contract.js file.
- Implemented the `wallet offer config`.
- Currently, I am having issues in allocating the amounts to the seat that on exit will trigger the wallet to transfer the minted payment to the card purse. Apparently, there is no function that can be used to allocate an amount to a single seat. 
- I tried to use the same logic as the atomic swap to allocate the amount but was unable to do so. 
---
### Todos
- Figure out a way to transfer the minted assets to the wallet. 
- Create the UI for the `Create` flow.

**Comment by danishyasin33** [comment]
> Added the 'Create' link in current flow: https://xd.adobe.com/view/d825c6e4-887c-4432-9c98-5fce91a25cb2-8d76/
> 
> @danishyasin33 please review

Provided feedback on Discord, there's an issue with how the attributes are designed.

**Comment by aamnasarosh** [comment]
Updates on the same XD link

**Comment by haseebasim** [comment]
### Update 28th January, 2022
---
- Was having issues before in transferring the minted payments to the wallet. So, worked on that and tried different approaches. 
- I was able to successfully store the minted NFT in the wallet by using the deposit facet of the purse that I obtained from the board. 
- After the NFT was stored in the wallet the purse notifiers that are already implemented detected the NFT and sent its details to the front-end so that it can be displayed in my cards section.
- Fixed a couple of UI issues, including Modal. The modal background was not covering the entire screen when the page was scrolled. Fixed that. 
- Adjusted the modal to contain large-size images. 
- Adjusted the overall height of the Modal to display information properly.
